# Generated by Django 4.0.4 on 2023-10-06 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserDetails',
            },
        ),
        migrations.CreateModel(
            name='ContactEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('personal_number', models.IntegerField(null=True)),
                ('company_name', models.TextField(null=True)),
                ('designation', models.TextField(null=True)),
                ('office_number', models.IntegerField(null=True)),
                ('whatsapp_number', models.IntegerField(null=True)),
                ('email', models.TextField(null=True)),
                ('website', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('profile_pic', models.FileField(null=True, upload_to='profile')),
                ('profile_pic_thubnail', models.FileField(null=True, upload_to='profile/thubnail')),
                ('cover_image', models.FileField(null=True, upload_to='coverimage')),
                ('url_slug', models.CharField(max_length=1000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ContactEntries',
            },
        ),
    ]
