# Generated by Django 4.0.4 on 2024-02-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('expiry_date', models.DateField(null=True)),
                ('contact_limit', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'Organizations',
            },
        ),
        migrations.AddField(
            model_name='userdetails',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
