# Generated by Django 4.0.4 on 2024-02-28 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_organizations_userdetails_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.organizations'),
        ),
    ]
