# Generated by Django 4.0.4 on 2024-02-28 11:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0004_alter_userdetails_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='Profile',
        ),
    ]
