# Generated by Django 4.0.4 on 2024-02-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_rename_userdetails_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactentries',
            old_name='profile_pic_thubnail',
            new_name='profile_pic_thumbnail',
        ),
    ]
