# Generated by Django 4.0.4 on 2024-03-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_rename_profile_pic_thubnail_contactentries_profile_pic_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialMedias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'social_medias',
            },
        ),
    ]
