# Generated by Django 4.0.4 on 2024-03-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_socialmedias'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedias',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
