# Generated by Django 4.0.4 on 2024-03-04 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_socialmedias_active'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='contactEntrySocialMedias',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('link', models.TextField()),
        #         ('active', models.BooleanField(default=True)),
        #         ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.socialmedias')),
        #     ],
        #     options={
        #         'db_table': 'contact_entry_social_medias',
        #     },
        # ),
        # migrations.AddField(
        #     model_name='contactentries',
        #     name='social_medias',
        #     field=models.ManyToManyField(null=True, to='portal.contact_entry_social_medias'),
        # ),
    ]
