# Generated by Django 4.0.4 on 2024-03-04 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('portal', '0011_contactentrysocialmedias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactentries',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cards'),
            preserve_default=False,
        ),
    ]
