# Generated by Django 4.0.4 on 2024-07-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_contactentries_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactentries',
            name='email2',
            field=models.TextField(null=True),
        ),
    ]
