# Generated by Django 3.2.16 on 2024-12-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_contactentries_email2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutomizedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('styles', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'customized_card_contact',
            },
        ),
        migrations.AddField(
            model_name='contactentries',
            name='about_me',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactentries',
            name='background_image',
            field=models.FileField(null=True, upload_to='background_images'),
        ),
        migrations.AddField(
            model_name='contactentries',
            name='company_logo',
            field=models.FileField(null=True, upload_to='company_logo'),
        ),
        migrations.AlterField(
            model_name='contactentries',
            name='office_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactentries',
            name='personal_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactentries',
            name='whatsapp_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
