# Generated by Django 4.0.4 on 2024-03-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='temp_image',
            field=models.ImageField(null=True, upload_to='card/template'),
        ),
    ]
